pipeline{
    agent any

    stages{
    
        stage('Test')
        {
            steps{
                sh 'mvn test'
            }

            

            post{
                always{
                    junit 'target/surefire-reports/*.xml'
                    sh 'junit-viewer --results=target/surefire-reports --save=reports.html'
                }
            }
        }
        

    }
}